#!/usr/bin/env python3
"""Generate the Merzarkabul Airplay Speakers single-cabinet KiCad schematic.

One cabinet: one ESP32-S3, one PCM5102A, four identical XH-A232 amplifiers
fed in parallel from the DAC, eight drivers, one programme (ADR-0002,
ADR-0021). Every amplifier, every C_SAFE and every pull-down is its own
connector or part so that ERC sees every net.

This is the electrical source of truth: real symbols, drawn wires, junctions
and power ports, so KiCad ERC actually checks connectivity instead of trusting
a wall of net labels. The readable one-page overview for documentation is a
separate artefact, generated by hardware/diagrams/generate_schematic_svg.py.

    python3 hardware/kicad/generate_merzarkabul.py            # write sources
    python3 hardware/kicad/generate_merzarkabul.py --validate # + ERC and PDF

Conventions used throughout
---------------------------
* Everything is placed on a 2.54 mm grid. kicad-sch-api snaps placements to the
  1.27 mm grid, so an off-grid placement would silently move a pin and leave a
  wire hanging next to it instead of on it. `GRID` and `on_grid()` enforce this.
* Wire endpoints are never hardcoded. They come from
  `schematic.get_component_pin_position()`, so the drawing stays correct even
  if a stock symbol's internal geometry differs from what we assumed.
* Purchased modules are drawn as connectors. Their pin ORDER is a logical design
  contract, not a claim about a seller board's physical header. Verify every
  silkscreen and datasheet before wiring hardware.
* Rails that would otherwise need a wire across the sheet use power symbols.
  Local connections are drawn as real wires.

Safety notes carried on the sheet itself
----------------------------------------
* BTL amplifier outputs are not ground. Never clip a scope ground to them.
* Drivers are not energised before G0-G2.
* The jack polarity is verified with a meter before the first power-up; the
  series reverse-polarity diode is a candidate until G1 measures its drop
  (ADR-0020).
* The adapter's no-load output is measured before it is ever connected and
  must read below 25.5 V: 24 V sits 2 V under the TPA3110's 26 V maximum
  (ADR-0020).
* The first energised path is one amplifier, one woofer and one tweeter; the
  other three amplifiers are wired to drivers only after G0-G2 pass on that
  pair.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import uuid as uuid_module
from dataclasses import dataclass, field
from pathlib import Path

try:
    import kicad_sch_api as ksa
except ModuleNotFoundError:  # pragma: no cover - environment guard
    sys.exit("kicad-sch-api is missing. Run: python -m pip install -r hardware/kicad/requirements.txt")

ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT = ROOT / "generated"

#: kicad-sch-api snaps to 1.27 mm; 2.54 keeps symbol pins on grid as well.
GRID = 2.54
SHEET_REV = "0.9-candidate"
SHEET_DATE = "2026-09-12"


def on_grid(value: float) -> float:
    return round(value / GRID) * GRID


def point(x: float, y: float) -> tuple[float, float]:
    return (on_grid(x), on_grid(y))


# ---------------------------------------------------------------------------
# Module definitions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Module:
    """A purchased board drawn as a generic connector.

    `pins` is the logical pin order. It is the interface contract for this
    design, not the physical header order of any specific seller revision.
    """

    reference: str
    value: str
    position: tuple[float, float]
    pins: tuple[str, ...]

    @property
    def size(self) -> int:
        return len(self.pins)

    def index(self, name: str) -> str:
        matches = [i for i, pin in enumerate(self.pins, start=1) if pin == name]
        if not matches:
            raise KeyError(f"{self.reference} has no pin on net {name!r}")
        if len(matches) > 1:
            raise KeyError(
                f"{self.reference} has {len(matches)} pins on net {name!r}; "
                "look the pin up by number instead of by net name")
        return str(matches[0])


MODULES: tuple[Module, ...] = (
    # ADR-0020. The jack is the whole power input: a 24 V / 2.9 A desktop
    # adapter on a 5.5x2.1 mm centre-positive barrel. There is no switch in V1;
    # the device is turned off by unplugging the adapter. The adapter's no-load
    # output is measured before it is connected and must read below 25.5 V.
    Module("J1", "DC INPUT JACK 5.5x2.1 / 24 V 2.9 A DESKTOP ADAPTER / CENTRE POSITIVE VERIFY / NO-LOAD < 25.5 V VERIFY", (46, 36),
           ("DC_IN", "POWER_GND")),
    # Two bucks, not one: a shared buck put audible hiss into the DAC on the
    # bench (owner's observation, ADR-0020). Buck A carries the USB backfeed
    # jumper because only the ESP devkit has USB; buck B feeds the DAC directly.
    Module("U3", "MP1584 BUCK A / ESP32-S3 / SET 5.10 V UNLOADED", (56, 96), ("VIN", "POWER_GND", "V5_A", "STAR_GND")),
    Module("U4", "MP1584 BUCK B / PCM5102A / SET 5.10 V UNLOADED / NO JUMPER", (56, 122), ("VIN", "POWER_GND", "V5_DAC", "STAR_GND")),
    Module("U5", "ESP32-S3 DEVKIT N16R8 / 16 MB FLASH + 8 MB PSRAM", (140, 100), (
        "V5_LOGIC", "STAR_GND", "ESP_3V3", "BUTTON_N", "LED_R", "LED_G", "LED_B",
        "I2S_BCLK", "I2S_LRCLK", "I2S_DATA",
        "DAC_XSMT",
    )),
    # XSMT is a pin on the module, not a note about it. ADR-0011 makes GPIO13
    # drive it and an external pull-down hold it, so it has to be in the netlist
    # or ERC is checking a circuit nobody is going to build.
    Module("U6", "PCM5102A I2S DAC MODULE / 3-WIRE PLL / MEASURE XSMT PAD BRIDGE BEFORE WIRING", (218, 100), (
        "I2S_BCLK", "I2S_LRCLK", "I2S_DATA", "STAR_GND", "V5_DAC", "STAR_GND",
        "DAC_XSMT", "DAC_LOUT", "DAC_ROUT", "DAC_AGND",
    )),
    # Four identical amplifiers on one DAC (ADR-0002): DAC_LOUT (woofer band)
    # into every L input, DAC_ROUT (tweeter band) into every R input. The board
    # has no mute or shutdown pin -- power in, audio in, speakers out -- so the
    # module lists exactly those and the only mute on the sheet is the DAC's
    # XSMT (ADR-0011).
    *(Module(f"U{7 + k}", f"XH-A232 #{k + 1} TPA3110 BTL AMP / 8-26 V / NO MUTE INPUT", (330, 92 + 26 * k), (
        "DAC_LOUT", "DAC_ROUT", "VIN", "POWER_GND",
        f"AMP{k + 1}_L_PLUS", f"AMP{k + 1}_L_MINUS", f"AMP{k + 1}_R_PLUS", f"AMP{k + 1}_R_MINUS",
    )) for k in range(4)),
    # One woofer and one tweeter per amplifier: J2/J3 on amp 1 ... J8/J9 on
    # amp 4. Each tweeter reaches its amplifier through its own C_SAFE.
    *(module for k in range(4) for module in (
        Module(f"J{2 + 2 * k}", f"WOOFER {k + 1} / 4 R CLASS / FS TBD / G0", (390, 86 + 26 * k),
               (f"AMP{k + 1}_L_PLUS", f"AMP{k + 1}_L_MINUS")),
        Module(f"J{3 + 2 * k}", f"TWEETER {k + 1} / 4 R CLASS / FS TBD / G2", (390, 102 + 26 * k),
               (f"TWEETER{k + 1}_POS", f"AMP{k + 1}_R_MINUS")),
    )),
    # Anodes carry the POST-resistor nets. Naming them LED_R/LED_G/LED_B here would
    # put the pre- and post-resistor net on one node and short out R3/R4/R5.
    Module("D1", "COMMON-CATHODE RGB STATUS LED", (140, 168), ("LED_R_A", "LED_G_A", "LED_B_A", "STAR_GND")),
)

#: Probe points TP0-TP33. The numbering is the single source shared with
#: docs/02-hardware/circuit-and-wiring-plan.md section 7.1 and the SVG sheet; a
#: mismatch here means the bring-up procedure and the schematic disagree, so
#: they are generated from one table.
TEST_POINTS: tuple[tuple[int, str], ...] = (
    # TP0 is the raw jack pin and TP1 the rail behind the reverse-polarity
    # candidate: the difference is D2's forward drop under load, which is the
    # G1 measurement that decides whether D2 stays or becomes a 0 R link.
    (0, "DC_IN"), (1, "VIN"), (2, "POWER_GND"),
    # One probe per buck output: the two 5 V rails are separate supplies.
    (3, "V5_A"), (4, "V5_DAC"),
    (5, "ESP_3V3"), (6, "I2S_BCLK"), (7, "I2S_LRCLK"), (8, "I2S_DATA"),
    # TP9/TP11 and TP10/TP12 are two probe points on one net: the DAC output
    # pad and the amplifier-bank end of the same bus, where the four inputs
    # are paralleled.
    (9, "DAC_LOUT"), (10, "DAC_ROUT"), (11, "DAC_LOUT"), (12, "DAC_ROUT"),
    # Four BTL pairs per amplifier, amp 1 first.
    *((13 + 4 * k + i, f"AMP{k + 1}_{net}")
      for k in range(4) for i, net in enumerate(("L_PLUS", "L_MINUS", "R_PLUS", "R_MINUS"))),
    (29, "BUTTON_N"), (30, "LED_R"), (31, "LED_G"), (32, "LED_B"),
    # TP33 is the mute line -- the only one, since the amplifiers have no mute
    # input. The only way to tell whether the pull-down is actually holding the
    # pad low through reset is to put a probe on it at power-up.
    (33, "DAC_XSMT"),
)

#: Nets that are deliberately left with a single connection. The set is empty:
#: every pin on this sheet has a counterpart, so anything appearing with one
#: pin is a wiring mistake, not an intentional stub. The set stays so that a
#: future reservation has a place to be declared instead of silencing the check.
EXPECTED_OPEN_NETS: frozenset[str] = frozenset()

SECTIONS: tuple[tuple[str, tuple[float, float], tuple[float, float]], ...] = (
    ("A. 24 V DC INPUT, REVERSE-POLARITY CANDIDATE AND BULK CAPACITOR  (ADR-0020)", (25, 15), (400, 70)),
    ("B. 5 V LOGIC SUPPLIES (TWO BUCKS)", (25, 78), (120, 150)),
    ("C. ESP32-S3 N16R8 AND USER INTERFACE  (ADR-0010)", (126, 78), (200, 190)),
    ("D. I2S DAC, FOUR BTL AMPS, DAC MUTE AND EIGHT DRIVERS  (ADR-0002, ADR-0011)", (208, 78), (400, 190)),
    ("E. TEST POINT ACCESS  TP0-TP33", (25, 196), (400, 250)),
)


@dataclass
class Builder:
    """Thin wrapper that keeps pin lookups and wiring in one place."""

    schematic: object
    modules: dict[str, Module] = field(default_factory=dict)

    # -- placement ---------------------------------------------------------
    def add_module(self, module: Module) -> None:
        self.schematic.components.add(
            lib_id=f"Connector_Generic:Conn_01x{module.size:02d}",
            reference=module.reference,
            value=module.value,
            position=point(*module.position),
        )
        self.modules[module.reference] = module
        for number, net in enumerate(module.pins, start=1):
            self.schematic.add_label(net, pin=(module.reference, str(number)), size=1.0)

    def add_part(self, lib_id: str, reference: str, value: str,
                 position: tuple[float, float], rotation: float = 0.0) -> None:
        self.schematic.components.add(lib_id=lib_id, reference=reference, value=value,
                                      position=point(*position), rotation=rotation)

    # -- lookup ------------------------------------------------------------
    def pin(self, reference: str, pin_number: str) -> tuple[float, float]:
        located = self.schematic.get_component_pin_position(reference, pin_number)
        if located is None:
            raise RuntimeError(f"pin {reference}.{pin_number} could not be located")
        return (float(located.x), float(located.y))

    def module_pin(self, reference: str, net: str) -> tuple[float, float]:
        return self.pin(reference, self.modules[reference].index(net))

    # -- connectivity ------------------------------------------------------
    def label(self, reference: str, pin_number: str, net: str) -> None:
        self.schematic.add_label(net, pin=(reference, pin_number), size=1.0)

    def wire(self, start: tuple[float, float], end: tuple[float, float]) -> None:
        self.schematic.add_wire(start, end)

    def route(self, start: tuple[float, float], end: tuple[float, float], channel: float) -> None:
        """Orthogonal horizontal-vertical-horizontal route through `channel`."""
        x = on_grid(channel)
        self.wire(start, (x, start[1]))
        self.wire((x, start[1]), (x, end[1]))
        self.wire((x, end[1]), end)

    def junction(self, position: tuple[float, float]) -> None:
        self.schematic.junctions.add(point(*position))

    def power(self, net: str, position: tuple[float, float], reference: str) -> tuple[float, float]:
        """Place a power symbol and return its pin, ready to wire."""
        lib_id = "power:GND" if net in ("POWER_GND", "STAR_GND", "DAC_AGND") else "power:PWR_FLAG"
        self.add_part(lib_id, reference, net, position)
        return self.pin(reference, "1")

    def text(self, message: str, position: tuple[float, float], *,
             size: float = 1.27, bold: bool = False) -> None:
        self.schematic.add_text(message, point(*position), size=size, bold=bold)


def draw_dc_input(builder: Builder) -> None:
    """Barrel jack, the reverse-polarity candidate and the bulk capacitor."""
    # D2 sits between the jack and VIN. It is a candidate: G1 decides between a
    # Schottky, an ideal-diode module and a plain 0 R link from the measured
    # drop and temperature. Whichever it is, the part has to exist in the
    # netlist -- without it DC_IN and VIN would be two nets with nothing between
    # them, and the sheet would draw an open circuit that ERC cannot see.
    # Device:D pin 1 is the cathode, pin 2 the anode; rotated so current flows
    # from the jack on the left towards the rail on the right.
    builder.add_part("Device:D_Schottky", "D2",
                     "REVERSE-POLARITY CANDIDATE / SCHOTTKY OR IDEAL DIODE OR 0 R LINK / DECIDE AT G1",
                     (100, 30), rotation=180)
    builder.label("D2", "2", "DC_IN")
    builder.label("D2", "1", "VIN")
    builder.route(builder.module_pin("J1", "DC_IN"), builder.pin("D2", "2"), 75)

    builder.add_part("Device:C_Polarized", "C1", "C_A / 1000 uF / 35 V / 105 C LOW-ESR TARGET", (150, 36))
    builder.label("C1", "1", "VIN")
    builder.label("C1", "2", "POWER_GND")
    builder.route(builder.pin("D2", "1"), builder.pin("C1", "1"), 130)

    builder.text("VERIFY CENTRE-POSITIVE POLARITY AT THE JACK WITH A METER BEFORE THE FIRST POWER-UP (G1). "
                 "Reading the adapter label is not a measurement.", (30, 58), bold=True)
    builder.text("MEASURE THE ADAPTER'S NO-LOAD OUTPUT BEFORE CONNECTING IT: below 25.5 V or it is refused. 24 V sits "
                 "2 V under the TPA3110's 26 V maximum (G1). 24 V is inside both windows: TPA3110 8-26 V, MP1584 4.5-28 V.", (30, 62), bold=True)
    builder.text("The adapter is given: 24 V / 2.9 A (about 70 W). The limiter ceiling is derived from that budget with all four "
                 "amps driven and verified by VIN sag in G1. No power switch in V1: unplug the adapter to turn off.", (30, 66))
    builder.text("First energisation from a current-limited lab supply, not the adapter. C_A is one part at the jack; "
                 "per-amp bulk only if the G1 ripple measurement asks for it. D2 at 2.9 A dissipates about 1 W or more.", (30, 69))


def draw_logic_supply(builder: Builder) -> None:
    """Two MP1584 5.10 V rails; the USB backfeed isolation jumper sits on buck A only."""
    builder.add_part("Connector_Generic:Conn_01x02", "JP1", "USB / SYSTEM 5 V ISOLATION JUMPER / BUCK A ONLY", (96, 96))
    builder.label("JP1", "1", "V5_A")
    builder.label("JP1", "2", "V5_LOGIC")
    builder.text("Adjust U3 and U4 to 5.10 V before connecting the ESP32 and DAC. "
                 "Keep JP1 open while programming over USB.", (28, 140))
    builder.text("Two bucks because a shared buck put audible hiss into the DAC on the bench (ADR-0020). "
                 "Buck B has no jumper: only the devkit has USB.", (28, 144))
    builder.text("TP3/TP4 target: <=50 mVpp under normal load; neither 5 V rail may dip below 4.75 V "
                 "on Wi-Fi current bursts.", (28, 148))


def draw_user_interface(builder: Builder) -> None:
    """Function button with its pull-up, and the RGB status LED series resistors."""
    builder.add_part("Switch:SW_Push", "SW1", "FUNCTION / PROVISION / RESET", (150, 150), rotation=90)
    builder.label("SW1", "1", "BUTTON_N")
    builder.label("SW1", "2", "STAR_GND")
    builder.add_part("Device:R", "R1", "10 k PULL-UP CANDIDATE", (150, 134), rotation=90)
    builder.label("R1", "1", "ESP_3V3")
    builder.label("R1", "2", "BUTTON_N")
    builder.add_part("Device:C", "C6", "C_DB / 100 nF HARDWARE DEBOUNCE / OPTIONAL", (166, 150), rotation=90)
    builder.label("C6", "1", "BUTTON_N")
    builder.label("C6", "2", "STAR_GND")
    # Pull-up, button and debounce cap share one node, so it is drawn as a node.
    builder.route(builder.pin("R1", "2"), builder.pin("SW1", "1"), 150)
    builder.route(builder.pin("R1", "2"), builder.pin("C6", "1"), 158)
    builder.junction(builder.pin("R1", "2"))

    for reference, value, net in (("R3", "R_R / 680 R CANDIDATE", "LED_R"),
                                  ("R4", "R_G / 330 R CANDIDATE", "LED_G"),
                                  ("R5", "R_B / 330 R CANDIDATE", "LED_B")):
        offset = ("LED_R", "LED_G", "LED_B").index(net)
        builder.add_part("Device:R", reference, value, (182 + offset * 14, 160), rotation=90)
        builder.label(reference, "1", net)
        builder.label(reference, "2", f"{net}_A")

    builder.text("Button and LED wiring is kept away from the Class-D speaker cables. "
                 "GPIO assignment is a candidate until the board schematic and a boot test exist.", (130, 182))
    builder.text("Series resistors are DNP if the purchased RGB module already carries them.", (130, 186))


def draw_audio_chain(builder: Builder) -> None:
    """DAC bus to four amplifier inputs, one C_SAFE per tweeter, one pull-down per amp."""
    # One series safety capacitor per tweeter, wired to its own driver
    # connector so that every tweeter's fuse is a part on the sheet: C2-C5 for
    # amps 1-4. The amplifier side is a label on the amp's R+ net.
    for k in range(4):
        n = k + 1
        reference = f"C{2 + k}"
        builder.add_part("Device:C", reference, f"C_SAFE {n} / NON-POLARISED FILM / 10 uF CANDIDATE UNTIL G2",
                         (372, 102 + 26 * k), rotation=90)
        builder.label(reference, "1", f"AMP{n}_R_PLUS")
        builder.label(reference, "2", f"TWEETER{n}_POS")
        builder.route(builder.pin(reference, "2"), builder.module_pin(f"J{3 + 2 * k}", f"TWEETER{n}_POS"), 382)

    # Notes sit under the DAC and the pull-downs, left of the amplifier column:
    # the column is full from top to bottom, so a line longer than that lane
    # would run across a connector symbol.
    notes = (
        ("DANGER: AMPn_L_MINUS / AMPn_R_MINUS on all four amps are BTL switching", True),
        ("outputs, not ground. Never clip a scope ground to them.", True),
        ("DAC_LOUT (woofer band) feeds the L input of all four XH-A232 in parallel,", False),
        ("DAC_ROUT (tweeter band) the four R inputs: one mono programme, two bands,", False),
        ("eight BTL channels (ADR-0002). Four 10 k class inputs in parallel are about", False),
        ("2.5 k, comfortable for the PCM5102A: arithmetic, G1 records the DAC level.", False),
        ("C_SAFE is not a crossover: last line of defence behind the DSP high-pass and", True),
        ("limiter, one per tweeter (C2-C5), value from the G2 report.", True),
        ("All four boards must be the same revision. First energised path: one amp, one", False),
        ("woofer, one tweeter; the other three reach drivers after G0-G2 pass on that pair.", False),
        ("MUTE: R6 is not optional. Every candidate GPIO leaves reset high-impedance", True),
        ("through ROM, bootloader and app init; the resistor holds mute, firmware only", True),
        ("RELEASES it (ADR-0011). Measure the XSMT pad to 3V3 before soldering; a hard", False),
        ("bridge makes GPIO13 fight the rail. XSMT is the ONLY mute in the chain: the", False),
        ("XH-A232 has no mute or shutdown input and is live from the moment VIN is.", False),
    )
    for index, (message, bold) in enumerate(notes):
        builder.text(message, (212, 132 + 4 * index), bold=bold)

    # ADR-0011. The pull-down is the mute; the GPIO only releases it. Drawn as
    # parts so they are ordered, stuffed and checked rather than remembered.
    builder.add_part("Device:R", "R6", "10 k PULL-DOWN / DAC XSMT / NOT OPTIONAL (ADR-0011)",
                     (240, 122), rotation=90)
    builder.label("R6", "1", "DAC_XSMT")
    builder.label("R6", "2", "STAR_GND")


def draw_test_points(builder: Builder) -> None:
    """One test point symbol per TP number, generated from the shared table."""
    for number, net in TEST_POINTS:
        # Twelve to a row: three rows for TP0-TP33, clear of the section's own
        # footer text. Fewer per row would push the last points onto it.
        column, row = number % 12, number // 12
        builder.add_part("Connector:TestPoint", f"TP{number}", net,
                         (34 + column * 30, 206 + row * 12))
        builder.label(f"TP{number}", "1", net)
    builder.text("Scope ground goes to POWER_GND or STAR_GND only. For BTL outputs (TP13-TP28) use a differential "
                 "probe, or two 10x probes with BOTH ground clips on TP2 and MATH = CH1 - CH2.",
                 (30, 244), bold=True)


def build_schematic():
    schematic = ksa.create_schematic("merzarkabul")
    schematic.set_paper_size("A3")
    schematic.set_title_block(
        title="Merzarkabul Airplay Speakers - Single Cabinet, Module Level",
        date=SHEET_DATE, rev=SHEET_REV, company="Merzarkabul Airplay Speakers",
        comments={
            1: "24 V / 2.9 A DC adapter -> 5.5x2.1 jack -> VIN | 2 x MP1584 | ESP32-S3 N16R8 | PCM5102A | 4 x XH-A232 | 8 drivers",
            2: "DO NOT ENERGISE DRIVERS BEFORE G0-G2. BTL OUTPUT NEGATIVES ARE NOT GROUND.",
            3: "Measure adapter no-load < 25.5 V and verify jack polarity before the first power-up (ADR-0020, G1).",
            4: "Generated by hardware/kicad/generate_merzarkabul.py - do not hand-edit the output.",
        },
    )
    builder = Builder(schematic)

    for title, start, end in SECTIONS:
        schematic.add_rectangle(point(*start), point(*end), stroke_width=0.35)
        schematic.add_text(title, point((start[0] + end[0]) / 2, start[1] + 3), size=2.2, bold=True)

    for module in MODULES:
        builder.add_module(module)

    draw_dc_input(builder)
    draw_logic_supply(builder)
    draw_user_interface(builder)
    draw_audio_chain(builder)
    draw_test_points(builder)

    # Rails that would otherwise need a wire across the whole sheet.
    for index, (net, position) in enumerate((
        ("VIN", (290, 46)), ("V5_LOGIC", (110, 96)), ("V5_DAC", (110, 122)), ("ESP_3V3", (128, 120)),
        ("POWER_GND", (290, 56)), ("STAR_GND", (110, 140)), ("DAC_AGND", (250, 128)),
    )):
        pin = builder.power(net, position, f"#PWR{index:02d}")
        builder.schematic.add_label(net, pin=(f"#PWR{index:02d}", "1"), size=1.0)
        del pin

    schematic.add_text(
        "G0 driver impedance curve and Fs BLOCKED | G1 dummy-load amp, adapter no-load, jack polarity, four-amp VIN sag and pop BLOCKED | "
        "G2 tweeter HPF and C_SAFE BLOCKED",
        point(30, 254), size=1.4, bold=True)
    schematic.add_text(
        "Module connectors show a logical interface, not a seller board's physical pin order. "
        "Confirm every silkscreen and datasheet before wiring hardware.",
        point(30, 258), size=1.27)
    return schematic


# ---------------------------------------------------------------------------
# Output and validation
# ---------------------------------------------------------------------------

def self_check(schematic) -> list[str]:
    """Structural checks that do not need KiCad installed.

    Catches the failure this drawing is most exposed to: a wire that renders
    next to a pin instead of on it, which looks connected but is not.
    """
    problems: list[str] = []

    pins: dict[tuple[float, float], str] = {}
    for component in schematic.components.all():
        # Probing past the last pin makes the library log a warning, so the pin
        # count is derived from the symbol name instead of discovered by trial.
        lib_id = str(getattr(component, "lib_id", ""))
        if lib_id.startswith("Connector_Generic:Conn_01x"):
            count = int(lib_id[-2:])
        elif lib_id.startswith(("power:", "Connector:TestPoint")):
            count = 1
        else:
            count = 2
        for number in range(1, count + 1):
            located = schematic.get_component_pin_position(component.reference, str(number))
            if located is None:
                problems.append(f"{component.reference}.{number} could not be located")
                continue
            pins[(round(float(located.x), 2), round(float(located.y), 2))] = f"{component.reference}.{number}"

    endpoints: set[tuple[float, float]] = set()
    for wire in schematic.wires:
        for end in (wire.start, wire.end):
            endpoints.add((round(float(end.x), 2), round(float(end.y), 2)))
    for endpoint in sorted(endpoints):
        if endpoint not in pins and not any(
            endpoint in (a, b) for a, b in _corner_pairs(schematic)
        ):
            problems.append(f"wire endpoint {endpoint} is neither a pin nor a routed corner")

    # Two different nets on one connection point silently merge into a single net.
    # That is how a series resistor gets shorted out while ERC still reports zero
    # errors, so it is checked here rather than left to KiCad.
    by_position: dict[tuple[float, float], set[str]] = {}
    net_sizes: dict[str, int] = {}
    for label in schematic.labels:
        key = (round(float(label.position.x), 2), round(float(label.position.y), 2))
        by_position.setdefault(key, set()).add(label.text)
        net_sizes[label.text] = net_sizes.get(label.text, 0) + 1
    for position, names in sorted(by_position.items()):
        if len(names) > 1:
            problems.append(
                f"{sorted(names)} share the connection point {position}: they become one net, "
                "so anything between them is shorted out")

    for net, size in sorted(net_sizes.items()):
        if size == 1 and net not in EXPECTED_OPEN_NETS:
            problems.append(
                f"net {net!r} has a single connection and is not in EXPECTED_OPEN_NETS; "
                "it is either unwired or a typo")

    numbers = [number for number, _ in TEST_POINTS]
    if numbers != list(range(len(numbers))):
        problems.append(f"test points must be a gapless TP0..TP{len(numbers) - 1} sequence")
    if len({number for number, _ in TEST_POINTS}) != len(TEST_POINTS):
        problems.append("duplicate test point number")

    for number, net in TEST_POINTS:
        if net not in net_sizes:
            problems.append(f"TP{number} names net {net!r}, which exists nowhere in the sheet")

    references = [component.reference for component in schematic.components.all()]
    duplicates = {ref for ref in references if references.count(ref) > 1}
    if duplicates:
        problems.append(f"duplicate reference designators: {sorted(duplicates)}")
    return problems


def _corner_pairs(schematic) -> set[tuple[tuple[float, float], tuple[float, float]]]:
    """Corners produced by orthogonal routing are shared by two wire segments."""
    counts: dict[tuple[float, float], int] = {}
    for wire in schematic.wires:
        for end in (wire.start, wire.end):
            key = (round(float(end.x), 2), round(float(end.y), 2))
            counts[key] = counts.get(key, 0) + 1
    shared = {key for key, count in counts.items() if count > 1}
    return {(key, key) for key in shared}


def locate_kicad_cli(explicit: str | None) -> str:
    if explicit:
        candidate = Path(explicit)
        if candidate.is_file():
            return str(candidate)
        raise FileNotFoundError(f"kicad-cli not found at {candidate}")
    found = shutil.which("kicad-cli")
    if found:
        return found
    searched: list[Path] = []
    if sys.platform.startswith("win"):
        searched = [Path(r"C:\Program Files\KiCad") / v / "bin" / "kicad-cli.exe"
                    for v in ("10.0", "9.0", "8.0")]
    elif sys.platform == "darwin":
        searched = [Path("/Applications/KiCad/kicad.app/Contents/MacOS/kicad-cli")]
    for candidate in searched:
        if candidate.is_file():
            return str(candidate)
    raise FileNotFoundError(
        "kicad-cli not found on PATH. Install KiCad 8 or newer, or pass --kicad-cli <path>.")


#: Fixed namespace for deterministic element UUIDs.
UUID_NAMESPACE = uuid_module.UUID("6f4d1b6e-2a3c-5d8f-9b41-7c2e0a5d3f18")
UUID_PATTERN = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")


def stabilise_uuids(schematic_path: Path) -> int:
    """Replace the library's random UUIDs with deterministic ones.

    The generated schematic is reviewed as a diff whenever it is regenerated and
    committed on a machine with KiCad. Left alone, every run emitted a
    fresh random UUID for every symbol, wire, label and junction, so simply
    re-running the generator produced an ~876 line diff with no design change in
    it, which buries the real change whenever there is one.

    Every UUID in the file is remapped through one table, so cross references
    stay intact: a symbol instance's `(path "/<sheet-uuid>")` still points at the
    sheet it belongs to. Replacing UUIDs one occurrence at a time would silently
    break that link.

    New values are assigned in order of first appearance. The generator is
    deterministic, so an unchanged script yields byte-identical output and the
    file only moves when the drawing actually moves. Inserting an element
    renumbers the ones after it, so review a regeneration diff as regenerated
    output rather than line by line.
    """
    text = schematic_path.read_text(encoding="utf-8")
    mapping: dict[str, str] = {}
    for found in UUID_PATTERN.findall(text):
        if found not in mapping:
            mapping[found] = str(uuid_module.uuid5(UUID_NAMESPACE, f"merzarkabul:{len(mapping)}"))
    stable = UUID_PATTERN.sub(lambda match: mapping[match.group(0)], text)
    schematic_path.write_text(stable, encoding="utf-8")
    return len(mapping)


def write_project(output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    schematic_path = output_dir / "merzarkabul.kicad_sch"
    project_path = output_dir / "merzarkabul.kicad_pro"
    build_schematic().save(schematic_path)
    stabilise_uuids(schematic_path)
    project = {"board": {}, "boards": [], "cvpcb": {}, "erc": {}, "libraries": {},
               "meta": {"filename": project_path.name, "version": 1}, "net_settings": {},
               "pcbnew": {}, "schematic": {}, "text_variables": {}}
    project_path.write_text(json.dumps(project, indent=2) + "\n", encoding="utf-8")
    return schematic_path


def run_checks(cli: str, schematic_path: Path) -> None:
    report = schematic_path.with_suffix(".erc.rpt")
    pdf = schematic_path.with_suffix(".pdf")
    erc = subprocess.run([cli, "sch", "erc", "--output", str(report), str(schematic_path)], check=False)
    report_text = report.read_text(encoding="utf-8")
    if "Errors 0" not in report_text:
        raise RuntimeError(f"KiCad ERC reported errors; inspect {report}")
    subprocess.run([cli, "sch", "export", "pdf", "--output", str(pdf), str(schematic_path)], check=True)
    print(f"ERC report: {report} (exit {erc.returncode}; unconnected TBD/NC pins are expected warnings)")
    print(f"Preview PDF: {pdf}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Merzarkabul Airplay Speakers KiCad schematic.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--validate", action="store_true", help="run KiCad ERC and export a PDF preview")
    parser.add_argument("--kicad-cli", help="explicit kicad-cli executable path")
    args = parser.parse_args()
    try:
        schematic = build_schematic()
        problems = self_check(schematic)
        for problem in problems:
            print(f"SELF-CHECK: {problem}", file=sys.stderr)
        if problems:
            return 1
        schematic_path = write_project(args.output_dir.resolve())
        print(f"Generated: {schematic_path}")
        print(f"Modules: {len(MODULES)} | test points: {len(TEST_POINTS)} | "
              f"self-check: {len(problems)} problems | deterministic output")
        if args.validate:
            run_checks(locate_kicad_cli(args.kicad_cli), schematic_path)
    except (FileNotFoundError, OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
