#!/usr/bin/env python3
"""Generate the Harman Kardom single-speaker KiCad schematic.

This is the electrical source of truth: real symbols, drawn wires, junctions
and power ports, so KiCad ERC actually checks connectivity instead of trusting
a wall of net labels. The readable one-page overview for documentation is a
separate artefact, generated by hardware/diagrams/generate_schematic_svg.py.

    python3 hardware/kicad/generate_harman_kardom.py            # write sources
    python3 hardware/kicad/generate_harman_kardom.py --validate # + ERC and PDF

Conventions used throughout
---------------------------
* Everything is placed on a 2.54 mm grid. kicad-sch-api snaps placements to the
  1.27 mm grid, so an off-grid placement would silently move a pin and leave a
  wire hanging next to it instead of on it. `GRID` and `on_grid()` enforce this.
* Wire endpoints are never hardcoded. They come from
  `schematic.get_component_pin_position()`, so the drawing stays correct even
  if a stock symbol's internal geometry differs from what we assumed.
* Purchased modules are drawn as connectors. Their pin ORDER is a logical design
  contract, not a claim about a seller board's physical header. Verify every
  silkscreen and datasheet before wiring hardware.
* Rails that would otherwise need a wire across the sheet use power symbols.
  Local connections are drawn as real wires.

Safety notes carried on the sheet itself
----------------------------------------
* BTL amplifier outputs are not ground. Never clip a scope ground to them.
* Drivers are not energised before G0-G2.
* V1 does not play audio while charging (ADR-0004).
* The XL4015 stage has no guaranteed charge termination (ADR-0009).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import uuid as uuid_module
from dataclasses import dataclass, field
from pathlib import Path

try:
    import kicad_sch_api as ksa
except ModuleNotFoundError:  # pragma: no cover - environment guard
    sys.exit("kicad-sch-api is missing. Run: python -m pip install -r hardware/kicad/requirements.txt")

ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT = ROOT / "generated"

#: kicad-sch-api snaps to 1.27 mm; 2.54 keeps symbol pins on grid as well.
GRID = 2.54
SHEET_REV = "0.6-candidate"
SHEET_DATE = "2026-08-31"


def on_grid(value: float) -> float:
    return round(value / GRID) * GRID


def point(x: float, y: float) -> tuple[float, float]:
    return (on_grid(x), on_grid(y))


# ---------------------------------------------------------------------------
# Module definitions
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Module:
    """A purchased board drawn as a generic connector.

    `pins` is the logical pin order. It is the interface contract for this
    design, not the physical header order of any specific seller revision.
    """

    reference: str
    value: str
    position: tuple[float, float]
    pins: tuple[str, ...]

    @property
    def size(self) -> int:
        return len(self.pins)

    def index(self, name: str) -> str:
        matches = [i for i, pin in enumerate(self.pins, start=1) if pin == name]
        if not matches:
            raise KeyError(f"{self.reference} has no pin on net {name!r}")
        if len(matches) > 1:
            raise KeyError(
                f"{self.reference} has {len(matches)} pins on net {name!r}; "
                "look the pin up by number instead of by net name")
        return str(matches[0])


MODULES: tuple[Module, ...] = (
    Module("J1", "USB-C PD INLET / EXTERNAL 65 W ADAPTER", (46, 36), ("USB_PD_VBUS", "POWER_GND")),
    Module("U1", "USB-C PD TRIGGER / FIXED 20 V", (99, 36), ("USB_PD_VBUS", "POWER_GND", "PD20V", "POWER_GND")),
    Module("U2", "XL4015 CC-CV / CALIBRATE 16.80 V 2.00 A", (155, 36), ("PD20V", "POWER_GND", "CHG_16V8", "POWER_GND")),
    Module("U3", "4S BALANCED BMS / COMMON PORT / VERIFY SILKSCREEN", (244, 33),
           ("BPLUS", "B3", "B2", "B1", "BMINUS", "PACK_POS", "POWER_GND", "NTC_BMS")),
    Module("U4", "MP1584 BUCK / SET 5.10 V UNLOADED", (56, 104), ("VBAT_SW", "POWER_GND", "V5_SYS", "STAR_GND")),
    Module("U5", "ESP32-S3 DEVKIT N16R8 / 16 MB FLASH + 8 MB PSRAM", (140, 100), (
        "V5_LOGIC", "STAR_GND", "ESP_3V3", "BUTTON_N", "LED_R", "LED_G", "LED_B",
        "I2S_BCLK", "I2S_LRCLK", "I2S_DATA", "I2C_SDA", "I2C_SCL",
        "AMP_MUTE", "DAC_XSMT", "BATT_SENSE", "NTC_SENSE",
    )),
    Module("U6", "PCM5102A I2S DAC MODULE / 3-WIRE PLL", (218, 100), (
        "I2S_BCLK", "I2S_LRCLK", "I2S_DATA", "STAR_GND", "V5_LOGIC", "STAR_GND",
        "DAC_LOUT", "DAC_ROUT", "DAC_AGND",
    )),
    Module("U7", "XH-A232 TPA3110 BTL AMP / 8-26 V", (300, 100), (
        "DAC_LOUT", "DAC_ROUT", "VBAT_SW", "POWER_GND",
        "AMP_L_PLUS", "AMP_L_MINUS", "AMP_R_PLUS", "AMP_R_MINUS", "AMP_SD_TBD",
    )),
    Module("J2", "WOOFER / IMPEDANCE TBD / G0", (360, 104), ("AMP_L_PLUS", "AMP_L_MINUS")),
    Module("J3", "TWEETER / IMPEDANCE TBD / G2", (360, 130), ("TWEETER_POS", "AMP_R_MINUS")),
    # Anodes carry the POST-resistor nets. Naming them LED_R/LED_G/LED_B here would
    # put the pre- and post-resistor net on one node and short out R3/R4/R5.
    Module("D1", "COMMON-CATHODE RGB STATUS LED", (140, 168), ("LED_R_A", "LED_G_A", "LED_B_A", "STAR_GND")),
)

#: Probe points TP0-TP27. The numbering is the single source shared with
#: docs/02-hardware/circuit-and-wiring-plan.md; a mismatch here means the bring-up
#: procedure and the schematic disagree, so they are generated from one table.
TEST_POINTS: tuple[tuple[int, str], ...] = (
    (0, "BMINUS"), (1, "B1"), (2, "B2"), (3, "B3"), (4, "BPLUS"),
    (5, "PACK_POS"), (6, "POWER_GND"), (7, "FUSED_POS"), (8, "VBAT_SW"), (9, "V5_SYS"),
    (10, "ESP_3V3"), (11, "I2S_BCLK"), (12, "I2S_LRCLK"), (13, "I2S_DATA"),
    # TP14/TP16 and TP15/TP17 are two probe points on one net: the DAC output pad
    # and the amplifier input pad of the same wire.
    (14, "DAC_LOUT"), (15, "DAC_ROUT"), (16, "DAC_LOUT"), (17, "DAC_ROUT"),
    (18, "AMP_L_PLUS"), (19, "AMP_L_MINUS"), (20, "AMP_R_PLUS"), (21, "AMP_R_MINUS"),
    (22, "BUTTON_N"), (23, "LED_R"), (24, "LED_G"), (25, "LED_B"),
    (26, "CHG_16V8"), (27, "NTC_BMS"),
)

#: Nets that are deliberately left with a single connection: reserved pins and
#: interfaces whose counterpart is still an open hardware decision. Anything else
#: appearing with one pin is a wiring mistake, not an intentional stub.
EXPECTED_OPEN_NETS: frozenset[str] = frozenset({
    "AMP_SD_TBD",    # XH-A232 shutdown pad; access not confirmed on the board
    "AMP_MUTE",      # GPIO21 reservation; its far end is AMP_SD_TBD, still unconfirmed
    "DAC_XSMT",      # GPIO13 reservation; PCM5102A XSMT, external pull-down holds mute
    "BATT_SENSE",    # GPIO1 reservation; divider ratio comes from G3/G4
    "NTC_SENSE",     # GPIO2 reservation; thermistor network comes from G4
    "I2C_SDA",       # optional INA226 telemetry
    "I2C_SCL",
})

SECTIONS: tuple[tuple[str, tuple[float, float], tuple[float, float]], ...] = (
    ("A. USB-C PD INPUT AND 16.80 V CC-CV CHARGE STAGE  (ADR-0009)", (25, 15), (200, 70)),
    ("B. 4S PACK, BALANCED BMS, FUSE AND HARD POWER SWITCH", (208, 15), (400, 70)),
    ("C. 5 V LOGIC SUPPLY", (25, 78), (120, 150)),
    ("D. ESP32-S3 N16R8 AND USER INTERFACE  (ADR-0010)", (126, 78), (200, 190)),
    ("E. I2S DAC, BTL BI-AMP AND DRIVERS  (ADR-0002)", (208, 78), (400, 150)),
    ("F. TEST POINT ACCESS  TP0-TP27", (25, 196), (400, 250)),
)


@dataclass
class Builder:
    """Thin wrapper that keeps pin lookups and wiring in one place."""

    schematic: object
    modules: dict[str, Module] = field(default_factory=dict)

    # -- placement ---------------------------------------------------------
    def add_module(self, module: Module) -> None:
        self.schematic.components.add(
            lib_id=f"Connector_Generic:Conn_01x{module.size:02d}",
            reference=module.reference,
            value=module.value,
            position=point(*module.position),
        )
        self.modules[module.reference] = module
        for number, net in enumerate(module.pins, start=1):
            self.schematic.add_label(net, pin=(module.reference, str(number)), size=1.0)

    def add_part(self, lib_id: str, reference: str, value: str,
                 position: tuple[float, float], rotation: float = 0.0) -> None:
        self.schematic.components.add(lib_id=lib_id, reference=reference, value=value,
                                      position=point(*position), rotation=rotation)

    # -- lookup ------------------------------------------------------------
    def pin(self, reference: str, pin_number: str) -> tuple[float, float]:
        located = self.schematic.get_component_pin_position(reference, pin_number)
        if located is None:
            raise RuntimeError(f"pin {reference}.{pin_number} could not be located")
        return (float(located.x), float(located.y))

    def module_pin(self, reference: str, net: str) -> tuple[float, float]:
        return self.pin(reference, self.modules[reference].index(net))

    # -- connectivity ------------------------------------------------------
    def label(self, reference: str, pin_number: str, net: str) -> None:
        self.schematic.add_label(net, pin=(reference, pin_number), size=1.0)

    def wire(self, start: tuple[float, float], end: tuple[float, float]) -> None:
        self.schematic.add_wire(start, end)

    def route(self, start: tuple[float, float], end: tuple[float, float], channel: float) -> None:
        """Orthogonal horizontal-vertical-horizontal route through `channel`."""
        x = on_grid(channel)
        self.wire(start, (x, start[1]))
        self.wire((x, start[1]), (x, end[1]))
        self.wire((x, end[1]), end)

    def junction(self, position: tuple[float, float]) -> None:
        self.schematic.junctions.add(point(*position))

    def power(self, net: str, position: tuple[float, float], reference: str) -> tuple[float, float]:
        """Place a power symbol and return its pin, ready to wire."""
        lib_id = "power:GND" if net in ("POWER_GND", "STAR_GND", "PD_GND", "DAC_AGND") else "power:PWR_FLAG"
        self.add_part(lib_id, reference, net, position)
        return self.pin(reference, "1")

    def text(self, message: str, position: tuple[float, float], *,
             size: float = 1.27, bold: bool = False) -> None:
        self.schematic.add_text(message, point(*position), size=size, bold=bold)


def draw_charge_stage(builder: Builder) -> None:
    """USB-C PD inlet, 20 V trigger, XL4015 CC/CV stage and the charge fuse."""
    builder.wire(builder.module_pin("J1", "USB_PD_VBUS"), builder.module_pin("U1", "USB_PD_VBUS"))
    builder.wire(builder.module_pin("U1", "PD20V"), builder.module_pin("U2", "PD20V"))
    # Ground hops are addressed by pin number: each converter carries POWER_GND on
    # both an input and an output pin, which is physically one plane inside the module.
    builder.wire(builder.pin("J1", "2"), builder.pin("U1", "2"))
    builder.wire(builder.pin("U1", "4"), builder.pin("U2", "2"))

    builder.add_part("Device:Fuse", "F2", "F_CHG / 3 A CANDIDATE", (196, 30), rotation=90)
    builder.label("F2", "1", "CHG_16V8")
    builder.label("F2", "2", "PACK_POS")

    builder.text("Set the PD trigger to 20 V and calibrate the XL4015 to 16.80 V / 2.00 A "
                 "WITH THE BATTERY DISCONNECTED.", (30, 62))
    builder.text("XL4015 HAS NO GUARANTEED CHARGE TERMINATION. Measure the CV current decay at G4; "
                 "no unattended charging before that.", (30, 66), bold=True)


def draw_pack_and_protection(builder: Builder) -> None:
    """Series cells, BMS taps, load fuse, hard switch and the bulk capacitor."""
    taps = (("BT1", "BPLUS", "B3"), ("BT2", "B3", "B2"), ("BT3", "B2", "B1"), ("BT4", "B1", "BMINUS"))
    for index, (reference, upper, lower) in enumerate(taps):
        builder.add_part("Device:Battery_Cell", reference,
                         f"ASPILSAN INR18650A28 / CELL {4 - index}", (216, 25 + index * 10))
        builder.label(reference, "1", upper)
        builder.label(reference, "2", lower)
    # The series string is drawn, not just labelled: adjacent cells sit on one
    # vertical line, so each link is a single straight wire.
    for upper_cell, lower_cell in zip(taps, taps[1:]):
        builder.wire(builder.pin(upper_cell[0], "2"), builder.pin(lower_cell[0], "1"))

    builder.add_part("Device:Fuse", "F1", "5 A STARTING CANDIDATE", (300, 25), rotation=90)
    builder.label("F1", "1", "PACK_POS")
    builder.label("F1", "2", "FUSED_POS")

    builder.add_part("Switch:SW_SPST", "S1",
                     "KM103 / DC-132A / CONTACT RATING UNDOCUMENTED / VERIFY 16.8 VDC 5 A", (325, 25), rotation=90)
    builder.label("S1", "1", "FUSED_POS")
    builder.label("S1", "2", "VBAT_SW")
    builder.route(builder.pin("F1", "2"), builder.pin("S1", "1"), 313)

    builder.add_part("Device:C_Polarized", "C1", "1000 uF / 25 V / 105 C LOW-ESR TARGET", (350, 30))
    builder.label("C1", "1", "VBAT_SW")
    builder.label("C1", "2", "POWER_GND")

    # Internal switch lamp: 12 V part on a 16.8 V rail, so it stays unfitted.
    builder.add_part("Device:LED", "D2", "KM103 INTERNAL 12 V LAMP / DNP", (372, 25), rotation=90)
    builder.label("D2", "2", "VBAT_SW")
    builder.label("D2", "1", "SW_LED_RETURN")
    builder.add_part("Device:R", "R2", "R_SW_LED / VALUE TBD / DNP", (372, 40), rotation=90)
    builder.label("R2", "1", "SW_LED_RETURN")
    builder.label("R2", "2", "POWER_GND")

    builder.text("BMS pin order is logical. Verify silkscreen, real continuous current, "
                 "balance threshold/current and NTC behaviour before wiring.", (212, 60))
    builder.text("D2 and R2 stay DNP: the switch lamp is a 12 V part and is never connected "
                 "directly to the 16.8 V rail.", (212, 64), bold=True)


def draw_logic_supply(builder: Builder) -> None:
    """MP1584 5.10 V rail and the USB backfeed isolation jumper."""
    builder.add_part("Connector_Generic:Conn_01x02", "JP1", "USB / SYSTEM 5 V ISOLATION JUMPER", (96, 100))
    builder.label("JP1", "1", "V5_SYS")
    builder.label("JP1", "2", "V5_LOGIC")
    builder.text("Adjust U4 to 5.10 V before connecting the ESP32 and DAC. "
                 "Keep JP1 open while programming over USB.", (28, 132))
    builder.text("TP9 target: <=50 mVpp under normal load; the 5 V rail must not dip below 4.75 V "
                 "on Wi-Fi current bursts.", (28, 136))


def draw_user_interface(builder: Builder) -> None:
    """Function button with its pull-up, and the RGB status LED series resistors."""
    builder.add_part("Switch:SW_Push", "SW1", "FUNCTION / PROVISION / RESET", (150, 150), rotation=90)
    builder.label("SW1", "1", "BUTTON_N")
    builder.label("SW1", "2", "STAR_GND")
    builder.add_part("Device:R", "R1", "10 k PULL-UP CANDIDATE", (150, 134), rotation=90)
    builder.label("R1", "1", "ESP_3V3")
    builder.label("R1", "2", "BUTTON_N")
    builder.add_part("Device:C", "C3", "C_DB / 100 nF HARDWARE DEBOUNCE / OPTIONAL", (166, 150), rotation=90)
    builder.label("C3", "1", "BUTTON_N")
    builder.label("C3", "2", "STAR_GND")
    # Pull-up, button and debounce cap share one node, so it is drawn as a node.
    builder.route(builder.pin("R1", "2"), builder.pin("SW1", "1"), 150)
    builder.route(builder.pin("R1", "2"), builder.pin("C3", "1"), 158)
    builder.junction(builder.pin("R1", "2"))

    for reference, value, net in (("R3", "R_R / 680 R CANDIDATE", "LED_R"),
                                  ("R4", "R_G / 330 R CANDIDATE", "LED_G"),
                                  ("R5", "R_B / 330 R CANDIDATE", "LED_B")):
        offset = ("LED_R", "LED_G", "LED_B").index(net)
        builder.add_part("Device:R", reference, value, (182 + offset * 14, 160), rotation=90)
        builder.label(reference, "1", net)
        builder.label(reference, "2", f"{net}_A")

    builder.text("Button, LED and I2C wiring is kept away from the Class-D speaker cables. "
                 "GPIO assignment is a candidate until the board schematic and a boot test exist.", (130, 182))
    builder.text("Series resistors are DNP if the purchased RGB module already carries them.", (130, 186))


def draw_audio_chain(builder: Builder) -> None:
    """DAC output to amplifier input, and the tweeter series safety capacitor."""
    builder.add_part("Device:C", "C2", "C_SAFE / NON-POLARISED FILM / VALUE TBD UNTIL G2", (338, 130), rotation=90)
    builder.label("C2", "1", "AMP_R_PLUS")
    builder.label("C2", "2", "TWEETER_POS")
    builder.route(builder.pin("C2", "2"), builder.module_pin("J3", "TWEETER_POS"), 348)

    builder.text("DANGER: AMP_L_MINUS and AMP_R_MINUS are BTL switching outputs, not ground. "
                 "Never clip a scope ground to them.", (212, 138), size=1.5, bold=True)
    builder.text("C_SAFE is not a crossover. It is the last line of defence behind the DSP high-pass "
                 "and limiter; its value comes from the G2 report.", (212, 142), bold=True)
    builder.text("Left digital channel drives the woofer path, right drives the tweeter path. "
                 "This is a bi-amp split of one mono program, not a stereo box.", (212, 146))


def draw_test_points(builder: Builder) -> None:
    """One test point symbol per TP number, generated from the shared table."""
    for number, net in TEST_POINTS:
        column, row = number % 10, number // 10
        builder.add_part("Connector:TestPoint", f"TP{number}", net,
                         (34 + column * 36, 210 + row * 12))
        builder.label(f"TP{number}", "1", net)
    builder.text("Scope ground goes to POWER_GND or STAR_GND only. For BTL outputs use a differential "
                 "probe, or two 10x probes with BOTH ground clips on TP6 and MATH = CH1 - CH2.",
                 (30, 246), bold=True)


def build_schematic():
    schematic = ksa.create_schematic("harman-kardom")
    schematic.set_paper_size("A3")
    schematic.set_title_block(
        title="Harman Kardom - Single Speaker, Module Level",
        date=SHEET_DATE, rev=SHEET_REV, company="Harman Kardom",
        comments={
            1: "USB-C PD -> XL4015 16.80 V CC/CV -> 4S BMS | ESP32-S3 N16R8 | PCM5102A | XH-A232 bi-amp",
            2: "DO NOT ENERGISE DRIVERS BEFORE G0-G2. BTL OUTPUT NEGATIVES ARE NOT GROUND.",
            3: "V1 does not play audio while charging (ADR-0004). XL4015 termination unproven (ADR-0009).",
            4: "Generated by hardware/kicad/generate_harman_kardom.py - do not hand-edit the output.",
        },
    )
    builder = Builder(schematic)

    for title, start, end in SECTIONS:
        schematic.add_rectangle(point(*start), point(*end), stroke_width=0.35)
        schematic.add_text(title, point((start[0] + end[0]) / 2, start[1] + 3), size=2.2, bold=True)

    for module in MODULES:
        builder.add_module(module)

    draw_charge_stage(builder)
    draw_pack_and_protection(builder)
    draw_logic_supply(builder)
    draw_user_interface(builder)
    draw_audio_chain(builder)
    draw_test_points(builder)

    # Rails that would otherwise need a wire across the whole sheet.
    for index, (net, position) in enumerate((
        ("VBAT_SW", (290, 46)), ("V5_LOGIC", (110, 96)), ("ESP_3V3", (128, 120)),
        ("POWER_GND", (290, 56)), ("STAR_GND", (110, 120)), ("DAC_AGND", (250, 128)),
    )):
        pin = builder.power(net, position, f"#PWR{index:02d}")
        builder.schematic.add_label(net, pin=(f"#PWR{index:02d}", "1"), size=1.0)
        del pin

    schematic.add_text(
        "G0 driver impedance BLOCKED | G1 dummy-load amp BLOCKED | G2 tweeter HPF and C_SAFE BLOCKED | "
        "G3 power, ripple, EMI BLOCKED | G4 battery, charge termination, NTC BLOCKED",
        point(30, 254), size=1.4, bold=True)
    schematic.add_text(
        "Module connectors show a logical interface, not a seller board's physical pin order. "
        "Confirm every silkscreen and datasheet before wiring hardware.",
        point(30, 258), size=1.27)
    return schematic


# ---------------------------------------------------------------------------
# Output and validation
# ---------------------------------------------------------------------------

def self_check(schematic) -> list[str]:
    """Structural checks that do not need KiCad installed.

    Catches the failure this drawing is most exposed to: a wire that renders
    next to a pin instead of on it, which looks connected but is not.
    """
    problems: list[str] = []

    pins: dict[tuple[float, float], str] = {}
    for component in schematic.components.all():
        # Probing past the last pin makes the library log a warning, so the pin
        # count is derived from the symbol name instead of discovered by trial.
        lib_id = str(getattr(component, "lib_id", ""))
        if lib_id.startswith("Connector_Generic:Conn_01x"):
            count = int(lib_id[-2:])
        elif lib_id.startswith(("power:", "Connector:TestPoint")):
            count = 1
        else:
            count = 2
        for number in range(1, count + 1):
            located = schematic.get_component_pin_position(component.reference, str(number))
            if located is None:
                problems.append(f"{component.reference}.{number} could not be located")
                continue
            pins[(round(float(located.x), 2), round(float(located.y), 2))] = f"{component.reference}.{number}"

    endpoints: set[tuple[float, float]] = set()
    for wire in schematic.wires:
        for end in (wire.start, wire.end):
            endpoints.add((round(float(end.x), 2), round(float(end.y), 2)))
    for endpoint in sorted(endpoints):
        if endpoint not in pins and not any(
            endpoint in (a, b) for a, b in _corner_pairs(schematic)
        ):
            problems.append(f"wire endpoint {endpoint} is neither a pin nor a routed corner")

    # Two different nets on one connection point silently merge into a single net.
    # That is how a series resistor gets shorted out while ERC still reports zero
    # errors, so it is checked here rather than left to KiCad.
    by_position: dict[tuple[float, float], set[str]] = {}
    net_sizes: dict[str, int] = {}
    for label in schematic.labels:
        key = (round(float(label.position.x), 2), round(float(label.position.y), 2))
        by_position.setdefault(key, set()).add(label.text)
        net_sizes[label.text] = net_sizes.get(label.text, 0) + 1
    for position, names in sorted(by_position.items()):
        if len(names) > 1:
            problems.append(
                f"{sorted(names)} share the connection point {position}: they become one net, "
                "so anything between them is shorted out")

    for net, size in sorted(net_sizes.items()):
        if size == 1 and net not in EXPECTED_OPEN_NETS:
            problems.append(
                f"net {net!r} has a single connection and is not in EXPECTED_OPEN_NETS; "
                "it is either unwired or a typo")

    numbers = [number for number, _ in TEST_POINTS]
    if numbers != list(range(len(numbers))):
        problems.append(f"test points must be a gapless TP0..TP{len(numbers) - 1} sequence")
    if len({number for number, _ in TEST_POINTS}) != len(TEST_POINTS):
        problems.append("duplicate test point number")

    for number, net in TEST_POINTS:
        if net not in net_sizes:
            problems.append(f"TP{number} names net {net!r}, which exists nowhere in the sheet")

    references = [component.reference for component in schematic.components.all()]
    duplicates = {ref for ref in references if references.count(ref) > 1}
    if duplicates:
        problems.append(f"duplicate reference designators: {sorted(duplicates)}")
    return problems


def _corner_pairs(schematic) -> set[tuple[tuple[float, float], tuple[float, float]]]:
    """Corners produced by orthogonal routing are shared by two wire segments."""
    counts: dict[tuple[float, float], int] = {}
    for wire in schematic.wires:
        for end in (wire.start, wire.end):
            key = (round(float(end.x), 2), round(float(end.y), 2))
            counts[key] = counts.get(key, 0) + 1
    shared = {key for key, count in counts.items() if count > 1}
    return {(key, key) for key in shared}


def locate_kicad_cli(explicit: str | None) -> str:
    if explicit:
        candidate = Path(explicit)
        if candidate.is_file():
            return str(candidate)
        raise FileNotFoundError(f"kicad-cli not found at {candidate}")
    found = shutil.which("kicad-cli")
    if found:
        return found
    searched: list[Path] = []
    if sys.platform.startswith("win"):
        searched = [Path(r"C:\Program Files\KiCad") / v / "bin" / "kicad-cli.exe"
                    for v in ("10.0", "9.0", "8.0")]
    elif sys.platform == "darwin":
        searched = [Path("/Applications/KiCad/kicad.app/Contents/MacOS/kicad-cli")]
    for candidate in searched:
        if candidate.is_file():
            return str(candidate)
    raise FileNotFoundError(
        "kicad-cli not found on PATH. Install KiCad 8 or newer, or pass --kicad-cli <path>.")


#: Fixed namespace for deterministic element UUIDs.
UUID_NAMESPACE = uuid_module.UUID("6f4d1b6e-2a3c-5d8f-9b41-7c2e0a5d3f18")
UUID_PATTERN = re.compile(r"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")


def stabilise_uuids(schematic_path: Path) -> int:
    """Replace the library's random UUIDs with deterministic ones.

    The generated schematic is committed to Git. Left alone, every run emitted a
    fresh random UUID for every symbol, wire, label and junction, so simply
    re-running the generator produced an ~876 line diff with no design change in
    it, which buries the real change whenever there is one.

    Every UUID in the file is remapped through one table, so cross references
    stay intact: a symbol instance's `(path "/<sheet-uuid>")` still points at the
    sheet it belongs to. Replacing UUIDs one occurrence at a time would silently
    break that link.

    New values are assigned in order of first appearance. The generator is
    deterministic, so an unchanged script yields byte-identical output and the
    file only moves when the drawing actually moves. Inserting an element
    renumbers the ones after it, so review a regeneration diff as regenerated
    output rather than line by line.
    """
    text = schematic_path.read_text(encoding="utf-8")
    mapping: dict[str, str] = {}
    for found in UUID_PATTERN.findall(text):
        if found not in mapping:
            mapping[found] = str(uuid_module.uuid5(UUID_NAMESPACE, f"harman-kardom:{len(mapping)}"))
    stable = UUID_PATTERN.sub(lambda match: mapping[match.group(0)], text)
    schematic_path.write_text(stable, encoding="utf-8")
    return len(mapping)


def write_project(output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    schematic_path = output_dir / "harman-kardom.kicad_sch"
    project_path = output_dir / "harman-kardom.kicad_pro"
    build_schematic().save(schematic_path)
    stabilise_uuids(schematic_path)
    project = {"board": {}, "boards": [], "cvpcb": {}, "erc": {}, "libraries": {},
               "meta": {"filename": project_path.name, "version": 1}, "net_settings": {},
               "pcbnew": {}, "schematic": {}, "text_variables": {}}
    project_path.write_text(json.dumps(project, indent=2) + "\n", encoding="utf-8")
    return schematic_path


def run_checks(cli: str, schematic_path: Path) -> None:
    report = schematic_path.with_suffix(".erc.rpt")
    pdf = schematic_path.with_suffix(".pdf")
    erc = subprocess.run([cli, "sch", "erc", "--output", str(report), str(schematic_path)], check=False)
    report_text = report.read_text(encoding="utf-8")
    if "Errors 0" not in report_text:
        raise RuntimeError(f"KiCad ERC reported errors; inspect {report}")
    subprocess.run([cli, "sch", "export", "pdf", "--output", str(pdf), str(schematic_path)], check=True)
    print(f"ERC report: {report} (exit {erc.returncode}; unconnected TBD/NC pins are expected warnings)")
    print(f"Preview PDF: {pdf}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the Harman Kardom KiCad schematic.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--validate", action="store_true", help="run KiCad ERC and export a PDF preview")
    parser.add_argument("--kicad-cli", help="explicit kicad-cli executable path")
    args = parser.parse_args()
    try:
        schematic = build_schematic()
        problems = self_check(schematic)
        for problem in problems:
            print(f"SELF-CHECK: {problem}", file=sys.stderr)
        if problems:
            return 1
        schematic_path = write_project(args.output_dir.resolve())
        print(f"Generated: {schematic_path}")
        print(f"Modules: {len(MODULES)} | test points: {len(TEST_POINTS)} | "
              f"self-check: {len(problems)} problems | deterministic output")
        if args.validate:
            run_checks(locate_kicad_cli(args.kicad_cli), schematic_path)
    except (FileNotFoundError, OSError, RuntimeError, subprocess.CalledProcessError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
